### PR TITLE
Stop generating autodocs

### PR DESCRIPTION
**Pull request by imobach**
No devel-doc package was generated and doc/autodocs is empty anyway, so I'm disabling autodocs generation.

### CODE REVIEW

**Comment by lslezak** [comment]
Please update the version and reference the FATE, we need to submit this package **before** `yast2-devtools`...

Otherwise LGTM.

**Comment by imobach** [comment]
Thanks. I've bumped the version and added the FATE reference.

**Comment by lslezak** [comment]
LGTM, thanks! :+1:

**Comment by imobach** [comment]
You're welcome! Merging...

**Pull request merged**
